version: 2.1
orbs:
  android: circleci/android@0.2.0
jobs:
  build:
    executor: android/android
    steps:
      - checkout
      - run:
          name: Run detekt
          command: ./gradlew detekt
      - run:
          name: Lints
          command: ./gradlew lint
      - run:
          name: Compile
          command: ./gradlew assemble
      - store_artifacts:
          path: build/reports
          destination: reports
      - store_artifacts:
          path: app/build/reports
          destination: app-reports
