name: Run lints and compile
on: [pull_request]
jobs:
  lint_dev_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache files
        uses: actions/cache@v2.1.0
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.android/build-cache
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}-${{ hashFiles('**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Gradle Initialization
        run: ./gradlew
      - name: Check forbidden comments
        run: ./gradlew checkStopShipXmls
      - name: Detekt
        run: ./gradlew detekt
      - name: Upload Detekt report
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Detekt report
          path: build/reports/detekt/detekt.html
      - name: Android Lints
        run: ./gradlew :app:lintDevDebug
      - name: Upload Lint report
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Lints report
          path: app/build/reports/lint-results-devDebug.html
  build_app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache files
        uses: actions/cache@v2.1.0
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.android/build-cache
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}-${{ hashFiles('**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build App
        run: ./gradlew build
      - name: Upload Report
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Lints report
          path: app/build/reports/
